(define (problem CafeProblem1)
     (:domain CafeDomain)
     (:objects 
	order1 order2 order3 order4 order5 - order
	margharita_pizza chicken ham_and_mushroom_pizza cod lasagne - dish
	chef1 chef2 - chef 
        ovenshelf1 ovenshelf2 ovenshelf3 - shelf
     )
     (:init
	;hard order
	(p_w_available order1)
	(ordered order1 ham_and_mushroom_pizza)
	(order_placed order1 ham_and_mushroom_pizza)
	(ordered order1 lasagne)
	(order_placed order1 lasagne)
	(ordered order1 cod)
	(order_placed order1 cod)
	;hard order
	(p_w_available order2)
	(ordered order2 ham_and_mushroom_pizza)
	(order_placed order2 ham_and_mushroom_pizza)
	(ordered order2 cod)
	(order_placed order2 cod)
	(ordered order2 chicken)
	(order_placed order2 chicken)
	;two shorts and a long order
	(p_w_available order3)
	(ordered order3 ham_and_mushroom_pizza)
	(order_placed order3 ham_and_mushroom_pizza)
	(ordered order3 margharita_pizza)
	(order_placed order3 margharita_pizza)
	(ordered order3 cod)
	(order_placed order3 cod)
	;two shorts and a long order
	(p_w_available order4)
	(ordered order4 ham_and_mushroom_pizza)
	(order_placed order4 ham_and_mushroom_pizza)
	(ordered order4 margharita_pizza)
	(order_placed order4 margharita_pizza)
	(ordered order4 lasagne)
	(order_placed order4 lasagne)
        (free ovenshelf1)
        (free ovenshelf2)
        (free ovenshelf3)
        (chef_free chef1)
        (chef_free chef2)
	(= (preparation_time margharita_pizza) 10)
	(= (cooking_time margharita_pizza) 10)
	(= (preparation_time chicken) 2)
	(= (cooking_time chicken) 30)
	(= (preparation_time ham_and_mushroom_pizza) 10)
	(= (cooking_time ham_and_mushroom_pizza) 12)
	(= (preparation_time cod) 3)
	(= (cooking_time cod) 24)
	(= (preparation_time lasagne) 4)
	(= (cooking_time lasagne) 28)
)
     (:goal (and
	(delivered order1 ham_and_mushroom_pizza)
	(delivered order1 lasagne)
	(delivered order1 cod)
	(delivered order2 ham_and_mushroom_pizza)
	(delivered order2 cod)
	(delivered order2 chicken)
	(delivered order3 ham_and_mushroom_pizza)
	(delivered order3 margharita_pizza)
	(delivered order3 cod)
	(delivered order4 ham_and_mushroom_pizza)
	(delivered order4 margharita_pizza)
	(delivered order4 lasagne)
          )
          
     )
     (:metric minimize (total-time))
     
)
